---
title: "Forecasting Time Series"
output:
  html_document: default
  pdf_document: default
  html_notebook: default
---

## Data Loading

```{r, echo=FALSE}
# You might need to install these packages in the Console first...
# install.packages("fBasics");  # basic statistics 
# install.packages("forecast");  # time series functions
# install.packages("fUnitRoots"); # for the adfTest function
library(fBasics);
library(forecast);
library(fUnitRoots);
```

```{r, echo = FALSE}
# You will need to change the following directory to match your file name location:
data <- read.csv("data.csv",header=TRUE,sep=";",dec=",");

# You will need to change the following row indexations to match the data.
# Recommended method: Use "View()" function to identify the # of rows in each series of data.
series1=data[,1][1:300];
series2=data[,2] [1:300];
series3=data[,3] [1:300];
series4=data[,4] [1:300];
series5=data[,5] [1:2000];
series6=data[,6];
series7=data[,7];
```

## Series 1

```{r}
y <- series1;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

## Series 2

```{r}
y <- series2;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

```{r}
# This additional code is required since ndiffs > 0 for this particular series.
# It performs the transformation (y --> z) and then applies the same tests as before.

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
ndiffs(z, alpha=0.05, test=c("adf"));
adfTest(z,lags=10,type=c("c"));
kurtosis(z,method=c("moment"));
shapiro.test(z)
Box.test (z, lag = 20, type="Ljung")
Box.test (z ^ 2, lag = 20, type="Ljung")

```

## Series 3

```{r}
y <- series3;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

```{r}
# This additional code is required since ndiffs > 0 for this particular series.
# It performs the transformation (y --> z) and then applies the same tests as before.

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
ndiffs(z, alpha=0.05, test=c("adf"));
adfTest(z,lags=10,type=c("c"));
kurtosis(z,method=c("moment"));
shapiro.test(z)
Box.test (z, lag = 20, type="Ljung")
Box.test (z ^ 2, lag = 20, type="Ljung")

```

## Series 4

```{r}
y <- series4;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

```{r}
# This additional code is required since ndiffs > 0 for this particular series.
# It performs the transformation (y --> z) and then applies the same tests as before.

d=2; # number of regular differences
z<-diff(y,d);
ts.plot(z);
ndiffs(z, alpha=0.05, test=c("adf"));
adfTest(z,lags=10,type=c("c"));
kurtosis(z,method=c("moment"));
shapiro.test(z)
Box.test (z, lag = 20, type="Ljung")
Box.test (z ^ 2, lag = 20, type="Ljung")

```

## Series 5

```{r}
y <- series5;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```


## Series 6

```{r}
y <- series6;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

## Series 7

```{r}
y <- series7;

mean(y);
sd(y);
skewness(y);
kurtosis(y,method=c("moment"));

# formal unit root test (Augmented Dickey Fuller test). Testing for stationarity.
# Ho: the process is not stationary. We need, at least, a unit root
# H1: the process is stationary. We have to check different models (lags)
adfTest(y,lags=10,type=c("c"));
ndiffs(y, alpha=0.05, test=c("adf"));

par(mar=c(1,1,1,1));
par(mfrow=c(3,1));
ts.plot(y);
acf(y);
pacf(y);

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
adfTest(z,lags=10,type=c("c"));

hist(y,prob=T,ylim=c(0,0.6),xlim=c(mean(y)-3*sd(y),mean(y)+3*sd(y)),col="red")
lines(density(y),lwd=2)
mu<-mean(y)
sigma<-sd(y)
x<-seq(mu-3*sigma,mu+3*sigma,length=100)
yy<-dnorm(x,mu,sigma)
lines(x,yy,lwd=2,col="blue")

# formal normality test
# Ho: the data is normally distributed
# H1: the data is not normally distributed
shapiro.test(y)

# formal test for white noise (zero autocorrelations)
# Ho: uncorrelated data
# H1: correlated data
Box.test (y, lag = 20, type="Ljung")
Box.test (y ^ 2, lag = 20, type="Ljung")

```

```{r}
# This additional code is required since ndiffs > 0 for this particular series.
# It performs the transformation (y --> z) and then applies the same tests as before.

d=1; # number of regular differences
z<-diff(y,d);
ts.plot(z);
ndiffs(z, alpha=0.05, test=c("adf"));
adfTest(z,lags=10,type=c("c"));
kurtosis(z,method=c("moment"));
shapiro.test(z)
Box.test (z, lag = 20, type="Ljung")
Box.test (z ^ 2, lag = 20, type="Ljung")

```